name: main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.x"
  AZURE_WEBAPP_NAME: "asc-dev-react"
  AZURE_WEBAPP_STORYBOOK_NAME: "asc-dev-react-storybook"

jobs:
  application:
    name: Prepare Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Restore Dependencies
        run: npm ci

      - name: Lint Application
        run: npm run lint -- --max-warnings 0

      - name: Run Unit Tests
        run: npm run test -- --coverage

      - name: Build Application
        run: npm run build

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: ./build

  storybook:
    name: Prepare Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Restore Dependencies
        run: npm ci

      - name: Lint Application
        run: npm run lint -- --max-warnings 0

      - name: Run Unit Tests
        run: npm run test -- --coverage

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook Artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: ./storybook-static

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [firefox, chrome, edge]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Restore Dependencies
        run: npm ci

      - name: Lint Integration Test
        run: npm run lint:e2e -- --max-warnings 0

      - name: Run Cypress on Browsers
        uses: cypress-io/github-action@v5
        with:
          start: npm run start
          browser: ${{ matrix.browser }}

  deploy_application:
    name: Deploy Application
    needs: [application, storybook, integration]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: application

      - name: Deploy Application
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  deploy_storybook:
    name: Deploy Storybook
    needs: [application, storybook, integration]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook

      - name: Deploy Application
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_STORYBOOK_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_STORYBOOK_PUBLISH_PROFILE }}
